# This is a Borland Makefile, not GNU

CC=C:\WATCOM19\BINW\WCC.EXE
LD=C:\WATCOM19\BINW\WLINK.EXE

CFLAGS = -0
  
OBJS = crc.obj disk.obj diskdump.obj dump.obj file.obj floppy.obj &
       hex.obj md5.obj mem.obj null.obj serial.obj sha1.obj &
			 sha256.obj stdout.obj

DEBUG_ENABLED = $(DEBUG)

!ifeq DEBUG 1  
CFLAGS += -d2
WLFLAGS = debug all option symfile
!endif

all: diskdump.exe
	
.c.obj:
	$(CC) $(CFLAGS) $< 

diskdump.exe: $(OBJS) 
	$(LD) $(WLFLAGS) file *.obj name $@ 
				
clean: .SYMBOLIC
  del *.obj > NUL
  del *.exe > NUL       
